spring:
  security:
    jwt:
      domain: higovip.com
      issuer: master
      secret: 934dhoUeop#45&*93==

server:
  port: 8001
  undertow:
    buffer-size: 1024
    io-threads: 8
    worker-threads: 256

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

logging:
  pattern:
    level: "[%5p]"
    dateformat: "[yyyy-MM-dd HH:mm:ss.SSS]"
  level:
    root: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
