server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

logging: # 日志
  pattern:
    level: "[%5p]"
    dateformat: "[yyyy-MM-dd HH:mm:ss.SSS]"
  level:
    root: DEBUG